/* ── Seed gyms data (frontend-only) ── */
import type { GymRecommendationItem } from "./gyms.types";

/** Hardcoded gyms dataset – will be replaced by an API call later */
export const SEED_GYMS: Omit<GymRecommendationItem, "distanceMeters">[] = [
  {
    id: "g-1",
    name: "Iron Forge Central",
    address: "Thamel",
    city: "Kathmandu",
    latitude: 27.7154,
    longitude: 85.3118,
    currentlyOpen: true,
    occupancyPercent: 65,
    occupancyLabel: "Moderately Busy",
    rating: 4.8,
    minimumAccessTier: "Pro",
    checkInEnabled: true,
    logoUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=400&fit=crop",
  },
  {
    id: "g-2",
    name: "Pulse Studios",
    address: "Maitighar",
    city: "Kathmandu",
    latitude: 27.6936,
    longitude: 85.3218,
    currentlyOpen: false,
    rating: 4.5,
    minimumAccessTier: "Pro",
    checkInEnabled: false,
    logoUrl: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=100&h=100&fit=crop",
  },
  {
    id: "3",
    name: "PowerHouse",
    address: "Lazimpat",
    city: "Kathmandu",
    latitude: 27.724,
    longitude: 85.321,
    currentlyOpen: false,
    occupancyPercent: 12,
    occupancyLabel: "Empty",
    minimumAccessTier: "Basic",
    checkInEnabled: true,
    logoUrl: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=100&h=100&fit=crop",
  },
  {
    id: "4",
    name: "Flex Factory",
    address: "New Road",
    city: "Kathmandu",
    latitude: 27.715,
    longitude: 85.345,
    currentlyOpen: true,
    occupancyPercent: undefined,
    occupancyLabel: undefined,
    minimumAccessTier: "Elite",
    checkInEnabled: true,
    logoUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=100&h=100&fit=crop",
  },
  {
    id: "5",
    name: "Olympia Fitness",
    address: "Jhamsikhel",
    city: "Lalitpur",
    latitude: 27.6688,
    longitude: 85.3188,
    currentlyOpen: true,
    occupancyPercent: 68,
    occupancyLabel: "Moderate",
    minimumAccessTier: "Pro",
    checkInEnabled: true,
    logoUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=100&h=100&fit=crop",
  },
];
